filter:
    paths: [src/*]
    excluded_paths: [examples/*, tests/*]
checks:
    php: true
tools:
    php_mess_detector: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [examples/*, tests/*]
    php_cpd:
        enabled: true
        excluded_dirs: [examples/*, tests/*]
    external_code_coverage:
        timeout: 600
        runs: 2
    php_code_sniffer:
        config:
            standard: "PSR2"
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run    